"""add horario_inicial and horario_final to horarios

Revision ID: 49f73ce3ef81
Revises: 72e90cf3fc35
Create Date: 2025-05-15 00:01:33.268706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f73ce3ef81'
down_revision = '72e90cf3fc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_inicial', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horario_final', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_column('horario_final')
        batch_op.drop_column('horario_inicial')

    # ### end Alembic commands ###
