"""Adiciona campo descricao em Servico

Revision ID: 5da7d7ca27cd
Revises: 93d8485816de
Create Date: 2025-05-10 03:26:54.771245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da7d7ca27cd'
down_revision = '93d8485816de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
