"""Separa data_hora em data e horas array em Agendamento

Revision ID: 72e90cf3fc35
Revises: 893ddc29a1f9
Create Date: 2025-05-11 08:06:41.133949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72e90cf3fc35'
down_revision = '893ddc29a1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('horas', postgresql.ARRAY(sa.Time()), nullable=False))
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('horas')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
