"""substitui servico_id por servico_ids

Revision ID: 843f0c56d2a9
Revises: e45e2b58e362
Create Date: 2025-05-03 00:10:29.001770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '843f0c56d2a9'
down_revision = 'e45e2b58e362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_ids', postgresql.ARRAY(sa.UUID()), nullable=False))
        batch_op.add_column(sa.Column('duracao', sa.Integer(), nullable=False))
        batch_op.drop_constraint('agendamentos_servico_id_fkey', type_='foreignkey')
        batch_op.drop_column('servico_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('agendamentos_servico_id_fkey', 'servicos', ['servico_id'], ['id'])
        batch_op.drop_column('duracao')
        batch_op.drop_column('servico_ids')

    # ### end Alembic commands ###
