"""Adiciona fk horario_id em agendamentos

Revision ID: 893ddc29a1f9
Revises: b5a69040b068
Create Date: 2025-05-11 07:44:23.579240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893ddc29a1f9'
down_revision = 'b5a69040b068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agendamentos_horario_id'), ['horario_id'], unique=False)
        batch_op.create_foreign_key(None, 'horarios', ['horario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agendamentos_horario_id'))
        batch_op.drop_column('horario_id')

    # ### end Alembic commands ###
