"""Cria tabela horarios e a tabela de funcionamento

Revision ID: b5a69040b068
Revises: 5da7d7ca27cd
Create Date: 2025-05-10 20:47:51.380486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5a69040b068'
down_revision = '5da7d7ca27cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionamentos',
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('menor_time', sa.Integer(), nullable=False),
    sa.Column('seg_inicio', sa.Time(), nullable=True),
    sa.Column('seg_fim', sa.Time(), nullable=True),
    sa.Column('ter_inicio', sa.Time(), nullable=True),
    sa.Column('ter_fim', sa.Time(), nullable=True),
    sa.Column('qua_inicio', sa.Time(), nullable=True),
    sa.Column('qua_fim', sa.Time(), nullable=True),
    sa.Column('qui_inicio', sa.Time(), nullable=True),
    sa.Column('qui_fim', sa.Time(), nullable=True),
    sa.Column('sex_inicio', sa.Time(), nullable=True),
    sa.Column('sex_fim', sa.Time(), nullable=True),
    sa.Column('sab_inicio', sa.Time(), nullable=True),
    sa.Column('sab_fim', sa.Time(), nullable=True),
    sa.Column('dom_inicio', sa.Time(), nullable=True),
    sa.Column('dom_fim', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funcionamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionamentos_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionamentos_id'), ['id'], unique=True)

    op.create_table('horarios',
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horarios', postgresql.ARRAY(sa.Time()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_colaborador_id'), ['colaborador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_estabelecimento_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_colaborador_id'))

    op.drop_table('horarios')
    with op.batch_alter_table('funcionamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionamentos_id'))
        batch_op.drop_index(batch_op.f('ix_funcionamentos_estabelecimento_id'))

    op.drop_table('funcionamentos')
    # ### end Alembic commands ###
