"""Migration inicial

Revision ID: dff91a342f2e
Revises: 
Create Date: 2025-04-27 02:11:28.662769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff91a342f2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimentos',
    sa.Column('email_login', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('pagarme_recipient_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email_login'),
    sa.UniqueConstraint('pagarme_recipient_id')
    )
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estabelecimentos_id'), ['id'], unique=True)

    op.create_table('clientes',
    sa.Column('email_login', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('pagarme_customer_id', sa.String(length=50), nullable=True),
    sa.Column('card_token', sa.String(length=100), nullable=True),
    sa.Column('card_last_digits', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email_login'),
    sa.UniqueConstraint('pagarme_customer_id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=True)

    op.create_table('colaboradores',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_id'), ['id'], unique=True)

    op.create_table('planos',
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ciclo_dias', sa.Integer(), nullable=False),
    sa.Column('pagarme_plan_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pagarme_plan_id')
    )
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planos_id'), ['id'], unique=True)

    op.create_table('servicos',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_id'), ['id'], unique=True)

    op.create_table('assinaturas',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('plano_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pagarme_subscription_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pagarme_subscription_id')
    )
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assinaturas_id'), ['id'], unique=True)

    op.create_table('agendamentos',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('estabelecimento_id', sa.UUID(), nullable=False),
    sa.Column('assinatura_id', sa.UUID(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_id'))

    op.drop_table('agendamentos')
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinaturas_id'))

    op.drop_table('assinaturas')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_id'))

    op.drop_table('servicos')
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planos_id'))

    op.drop_table('planos')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_id'))

    op.drop_table('colaboradores')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estabelecimentos_id'))

    op.drop_table('estabelecimentos')
    # ### end Alembic commands ###
