"""Inclusão do campo de ID da base

Revision ID: e45e2b58e362
Revises: dff91a342f2e
Create Date: 2025-04-27 05:20:28.337214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45e2b58e362'
down_revision = 'dff91a342f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_base', sa.String(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_estabelecimentos_identificador_base'), ['identificador_base'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estabelecimentos_identificador_base'))
        batch_op.drop_column('identificador_base')

    # ### end Alembic commands ###
